title: Jan Harold Alcantara
position: Postdoctoral Scholar
affiliation: Institute of Statistical Science, Academia Sinica
email: janharold (at) stat.sinica.edu.tw
keywords: minimal academic
research_gate: https://www.researchgate.net/profile/Jan-Harold-Alcantara?ev=hdr_xprf&_sg=VoLifvuLNWtcyTncwUNty7w79YKFXolIPR5cM_4s_QUvzKj4npi2MiM0f3EbmiaE4Q0M3AGM6LdzySPTyUd5Nv2_
description: The Minimal Light is a simple and elegant jekyll theme for academic personal homepage.
canonical: https://minimal-light.yyliu.net/
remote_theme: yaoyao-liu/minimal-light
