title: Jan Harold Alcantara
position: Postdoctoral Scholar
affiliation: Academia Sinica
email: janharold@stat.sinica.edu.tw -or- jan.harold.alcantara@gmail.com
keywords: Jan Harold Alcantara
google_scholar: https://scholar.google.com.ph/citations?user=E6oQznwAAAAJ&hl=en
google_analytics: UA-231930163-1
description: Jan Harold's Homepage
canonical: https://jhalcantara.github.io
remote_theme: yaoyao-liu/minimal-light
