title: Dooby Santos Doo
position: boss of all humans
email: yourname (at) example.edu
keywords: minimal academic
google_scholar: https://scholar.google.com.ph/citations?user=E6oQznwAAAAJ&hl=en
is_project_page: false
canonical: https://minimal-light.yyliu.net/
remote_theme: yaoyao-liu/minimal-light
